apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "tmpServiceName"
  namespace: "prod"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "tmpServiceName"
  template:
    metadata:
      labels:
        app: "tmpServiceName"
    spec:
      containers:
        - name: "tmpServiceName"
          image: "tmpServiceNameImage"
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: "/health"
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            limits:
              cpu: "100m"
              memory: 256Mi
            requests:
              cpu: "10m"
              memory: 64Mi
          env:
            - name: "SERVICE_NAME"
              value: "tmpServiceName"
          envFrom:
            - configMapRef:
                name: config-map
