apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "example1"
  namespace: "qa"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "example1"
  template:
    metadata:
      labels:
        app: "example1"
    spec:
      containers:
        - name: "example1"
          image: "itayp/example1:1.0.0"
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: "/health"
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: "SERVICE_NAME"
              value: "example1"
          envFrom:
            - configMapRef:
                name: example1-config-map
